<?php
return array (
  67 => 
  array (
    'id' => '67',
    'catid' => '38',
    'typeid' => '0',
    'title' => '省部级科技进步奖71项',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '111111111111111111111111',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=38&id=67',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470981320',
    'updatetime' => '1470986534',
    'hitsid' => 'c-1-67',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  69 => 
  array (
    'id' => '69',
    'catid' => '38',
    'typeid' => '0',
    'title' => '集团获得5项2011年度中施企协科学技术奖技术创新成果',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '3333333333333333333',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=38&id=69',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470981346',
    'updatetime' => '1470986539',
    'hitsid' => 'c-1-69',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  68 => 
  array (
    'id' => '68',
    'catid' => '38',
    'typeid' => '0',
    'title' => '国家技术发明奖二等奖1项',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '22222222222222',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=38&id=68',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470981337',
    'updatetime' => '1470981344',
    'hitsid' => 'c-1-68',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  70 => 
  array (
    'id' => '70',
    'catid' => '38',
    'typeid' => '0',
    'title' => '集团获得9项中国施工企业管理协会科学技术奖表彰',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '5555555555555555555555555',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=38&id=70',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470981357',
    'updatetime' => '1470981363',
    'hitsid' => 'c-1-70',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  71 => 
  array (
    'id' => '71',
    'catid' => '38',
    'typeid' => '0',
    'title' => '集团4项科技成果获2009年度广州市科学技术奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '6666666666666666666',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=38&id=71',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470981365',
    'updatetime' => '1470981371',
    'hitsid' => 'c-1-71',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  72 => 
  array (
    'id' => '72',
    'catid' => '38',
    'typeid' => '0',
    'title' => '市建科研院两项成果获奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '5555555555555555',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=38&id=72',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470981373',
    'updatetime' => '1470981378',
    'hitsid' => 'c-1-72',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>