<?php
return array (
  9 => 
  array (
    'id' => '9',
    'catid' => '32',
    'typeid' => '0',
    'title' => '朱小丹省长、温国辉市长考察广州建筑援疆项目',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '6月3日，朱小丹省长率广东省政府代表团赴新疆喀什地区考察对口援疆工作，期间考察了位于疏附县的广州市建筑集团产业援疆项目广州新城。省委   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470967685',
    'updatetime' => '1470985197',
    'hitsid' => 'c-1-9',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团公司营改增专题培训会',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2016/0813/20160813020451918.jpg',
    'keywords' => '',
    'description' => '为贯彻落实&ldquo;营业税改征增值税&rdquo;相关税改精神，有效规避各类税务风险，保证集团公司税制转换的平稳过渡。集团公司于4月22日-4月23日，在建   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470967720',
    'updatetime' => '1470986630',
    'hitsid' => 'c-1-11',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '32',
    'typeid' => '0',
    'title' => '广州驰援深圳山体滑坡灾害一线',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '101010',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470969075',
    'updatetime' => '1470973240',
    'hitsid' => 'c-1-17',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团公司喜获“2015年度广东省优秀企业和诚信示范企业"',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '2016年5月11日在第22届广东省企业家活动日上，广州市建筑集团有限公司被授予&ldquo;二零一五年度广东省优秀企业&rdquo;和荣获&ldquo;广东省诚信示范企业&rdquo;   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470967700',
    'updatetime' => '1470968166',
    'hitsid' => 'c-1-10',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团与新疆维吾尔自治区交通规划勘察设计研究院签订战略',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2016/0813/20160813020520531.jpg',
    'keywords' => '',
    'description' => '4月14日，新疆维吾尔自治区交通规划勘察设计研究院宋学艺院长一行到集团商务拜访。集团公司梁湖清总经理、杨粤黔副总经理携市政集团、总承   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470967736',
    'updatetime' => '1470968162',
    'hitsid' => 'c-1-12',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '32',
    'typeid' => '0',
    'title' => '2015年集团公司喜获6项广州市科学技术奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => ' 广州市科技创新委员会发布了&ldquo;关于2015年广州市科学技术奖拟奖项目公示的通知&rdquo;，其集团公司共获得6项科技奖公示上榜，其中一等奖1项：广   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470969037',
    'updatetime' => '1470969157',
    'hitsid' => 'c-1-14',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团召开2015年度工作会议',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2016/0813/20160813020622584.jpg',
    'keywords' => '',
    'description' => ' 2015年12月30日下午，集团在建工大厦八楼礼堂召开年度工作会议。会议由集团公司刘玉贵副总经理主持。集团公司领导班子成员，监事会，总部   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470969060',
    'updatetime' => '1470969073',
    'hitsid' => 'c-1-16',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团公司获2015年度全国优秀博士后工作站',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '广州市建筑集团有限公司企业博士后工作站被评为2015年度全国优秀博士后工作站。',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470969045',
    'updatetime' => '1470969058',
    'hitsid' => 'c-1-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '32',
    'typeid' => '0',
    'title' => '市国资委周建军主任视察广州建筑',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2016/0813/20160813020551713.jpg',
    'keywords' => '',
    'description' => '666666666666666666666666',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470968989',
    'updatetime' => '1470968995',
    'hitsid' => 'c-1-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团召开2016年上半年工作会议暨党建工作表彰会议',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2016/0813/20160813020327965.jpg',
    'keywords' => '',
    'description' => '2016年7月15日下午，集团在建工大厦八楼礼堂召开2016年上半年工作会议暨党建工作表彰会议。会 议由集团公司刘玉贵副总经理主持。集团公   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470967645',
    'updatetime' => '1470967679',
    'hitsid' => 'c-1-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>