<?php
return array (
  18 => 
  array (
    'id' => '18',
    'catid' => '33',
    'typeid' => '0',
    'title' => '广州建筑股份有限公司“超高空屋顶超长天线提升施工方法',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => ' 国家知识产权局发布了&ldquo;关于第十七届中国专利奖授奖的决定&rdquo;（国知发管字[2015]67号），决定授予20项发明、实用新型专利中国专利金奖，5   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972219',
    'updatetime' => '1470972349',
    'hitsid' => 'c-1-18',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  26 => 
  array (
    'id' => '26',
    'catid' => '33',
    'typeid' => '0',
    'title' => '广州建筑股份有限公司及广州一建公司双双荣获两个省级大',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '近日，从广东省建筑业协会五届二次理事会暨创优经验交流大会上传来喜讯：广州建筑股份有限公司（以下简称&ldquo;股份公司&rdquo;）、广州市第一建筑工   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=26',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972491',
    'updatetime' => '1470972501',
    'hitsid' => 'c-1-26',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  25 => 
  array (
    'id' => '25',
    'catid' => '33',
    'typeid' => '0',
    'title' => '市政集团捧回2个“金杯”',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '中国市政工程协会公布了2015年度&ldquo;全国市政金杯示范工程&rdquo;获奖项目名单，共有92项，市政集团三公司、机施公司的珠海市三灶镇安基路东段道路   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972476',
    'updatetime' => '1470972489',
    'hitsid' => 'c-1-25',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  24 => 
  array (
    'id' => '24',
    'catid' => '33',
    'typeid' => '0',
    'title' => '市住建委李敏霞总工程师带队到广州一建公司调研',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '88888888888888888888888888888',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=24',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972464',
    'updatetime' => '1470972474',
    'hitsid' => 'c-1-24',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '33',
    'typeid' => '0',
    'title' => '机施集团多个项目获奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '机施集团医院工程1幢、广州市寺右公馆住宅项目等16个项目荣获广州市&ldquo;2015年度平安工地&rdquo;称号。另，机施集团 &ldquo;中国南方航空大厦&rdquo;、中山   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972453',
    'updatetime' => '1470972462',
    'hitsid' => 'c-1-23',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '33',
    'typeid' => '0',
    'title' => '中广国际澳职所获奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '&lt;p&gt;中广国际澳职所荣获2015年内地输澳劳务管理工作服务维权奖和荣誉贡献奖两项大奖。&lt; p&gt;',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972441',
    'updatetime' => '1470972451',
    'hitsid' => 'c-1-22',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  21 => 
  array (
    'id' => '21',
    'catid' => '33',
    'typeid' => '0',
    'title' => '建材公司获2015年度广东省优秀信用企业',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '建材公司获得由第六届华南信用管理论坛组委会、广东省现代服务业联合会授予的“2015年度广东省优秀信用企业”荣誉称号，已连续4年获此殊荣。',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=21',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972429',
    'updatetime' => '1470972439',
    'hitsid' => 'c-1-21',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  20 => 
  array (
    'id' => '20',
    'catid' => '33',
    'typeid' => '0',
    'title' => '一建公司2015年科技创新成果显著',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '一建公司科技创新成果显著。在2015年申报的3个&ldquo;2014年度中国施工企业管理协会科学技术奖&rdquo;项目全部获奖，其中，《建筑幕墙工程绿色施工关   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972414',
    'updatetime' => '1470972427',
    'hitsid' => 'c-1-20',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  19 => 
  array (
    'id' => '19',
    'catid' => '33',
    'typeid' => '0',
    'title' => '广州市建筑科学研究院有限公司获批广州市第四批广州市博',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '广州市人力资源和社会保障局发布&ldquo;关于公布第四批广州市博士后创新实践基地的通知&rdquo;（穗人社函〔2015〕2462号），广州市建筑科学研究院有限   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=19',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972357',
    'updatetime' => '1470972412',
    'hitsid' => 'c-1-19',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  27 => 
  array (
    'id' => '27',
    'catid' => '33',
    'typeid' => '0',
    'title' => '喜获省土木学会科技一等奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '广东省土木建筑学会公布了2016年度（第四届）科学技术奖获奖名单，机施集团1项成果获得一等奖，这已是机施集团第二次获得此殊荣。另外，还   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=27',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972503',
    'updatetime' => '1470972512',
    'hitsid' => 'c-1-27',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>