<?php
return array (
  9 => 
  array (
    'id' => '9',
    'catid' => '32',
    'typeid' => '0',
    'title' => '朱小丹省长、温国辉市长考察广州建筑援疆项目',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '6月3日，朱小丹省长率广东省政府代表团赴新疆喀什地区考察对口援疆工作，期间考察了位于疏附县的广州市建筑集团产业援疆项目广州新城。省委   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470967685',
    'updatetime' => '1470985197',
    'hitsid' => 'c-1-9',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团公司营改增专题培训会',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2016/0813/20160813020451918.jpg',
    'keywords' => '',
    'description' => '为贯彻落实&ldquo;营业税改征增值税&rdquo;相关税改精神，有效规避各类税务风险，保证集团公司税制转换的平稳过渡。集团公司于4月22日-4月23日，在建   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470967720',
    'updatetime' => '1470986630',
    'hitsid' => 'c-1-11',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '32',
    'typeid' => '0',
    'title' => '2015年集团公司喜获6项广州市科学技术奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => ' 广州市科技创新委员会发布了&ldquo;关于2015年广州市科学技术奖拟奖项目公示的通知&rdquo;，其集团公司共获得6项科技奖公示上榜，其中一等奖1项：广   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470969037',
    'updatetime' => '1470969157',
    'hitsid' => 'c-1-14',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团公司喜获“2015年度广东省优秀企业和诚信示范企业"',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '2016年5月11日在第22届广东省企业家活动日上，广州市建筑集团有限公司被授予&ldquo;二零一五年度广东省优秀企业&rdquo;和荣获&ldquo;广东省诚信示范企业&rdquo;   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470967700',
    'updatetime' => '1470968166',
    'hitsid' => 'c-1-10',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团与新疆维吾尔自治区交通规划勘察设计研究院签订战略',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2016/0813/20160813020520531.jpg',
    'keywords' => '',
    'description' => '4月14日，新疆维吾尔自治区交通规划勘察设计研究院宋学艺院长一行到集团商务拜访。集团公司梁湖清总经理、杨粤黔副总经理携市政集团、总承   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470967736',
    'updatetime' => '1470968162',
    'hitsid' => 'c-1-12',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '32',
    'typeid' => '0',
    'title' => '广州驰援深圳山体滑坡灾害一线',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '101010',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470969075',
    'updatetime' => '1470973240',
    'hitsid' => 'c-1-17',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '33',
    'typeid' => '0',
    'title' => '机施集团多个项目获奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '机施集团医院工程1幢、广州市寺右公馆住宅项目等16个项目荣获广州市&ldquo;2015年度平安工地&rdquo;称号。另，机施集团 &ldquo;中国南方航空大厦&rdquo;、中山   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972453',
    'updatetime' => '1470972462',
    'hitsid' => 'c-1-23',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  24 => 
  array (
    'id' => '24',
    'catid' => '33',
    'typeid' => '0',
    'title' => '市住建委李敏霞总工程师带队到广州一建公司调研',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '88888888888888888888888888888',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=24',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972464',
    'updatetime' => '1470972474',
    'hitsid' => 'c-1-24',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  25 => 
  array (
    'id' => '25',
    'catid' => '33',
    'typeid' => '0',
    'title' => '市政集团捧回2个“金杯”',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '中国市政工程协会公布了2015年度&ldquo;全国市政金杯示范工程&rdquo;获奖项目名单，共有92项，市政集团三公司、机施公司的珠海市三灶镇安基路东段道路   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972476',
    'updatetime' => '1470972489',
    'hitsid' => 'c-1-25',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  26 => 
  array (
    'id' => '26',
    'catid' => '33',
    'typeid' => '0',
    'title' => '广州建筑股份有限公司及广州一建公司双双荣获两个省级大',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '近日，从广东省建筑业协会五届二次理事会暨创优经验交流大会上传来喜讯：广州建筑股份有限公司（以下简称&ldquo;股份公司&rdquo;）、广州市第一建筑工   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=26',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972491',
    'updatetime' => '1470972501',
    'hitsid' => 'c-1-26',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  37 => 
  array (
    'id' => '37',
    'catid' => '34',
    'typeid' => '0',
    'title' => '1～6月份全国固定资产投资增长9%',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '11111111111111111111111111111111111111111',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=37',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470973053',
    'updatetime' => '1470973064',
    'hitsid' => 'c-1-37',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  27 => 
  array (
    'id' => '27',
    'catid' => '33',
    'typeid' => '0',
    'title' => '喜获省土木学会科技一等奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '广东省土木建筑学会公布了2016年度（第四届）科学技术奖获奖名单，机施集团1项成果获得一等奖，这已是机施集团第二次获得此殊荣。另外，还   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=27',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972503',
    'updatetime' => '1470972512',
    'hitsid' => 'c-1-27',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '33',
    'typeid' => '0',
    'title' => '中广国际澳职所获奖',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '&lt;p&gt;中广国际澳职所荣获2015年内地输澳劳务管理工作服务维权奖和荣誉贡献奖两项大奖。&lt; p&gt;',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972441',
    'updatetime' => '1470972451',
    'hitsid' => 'c-1-22',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  21 => 
  array (
    'id' => '21',
    'catid' => '33',
    'typeid' => '0',
    'title' => '建材公司获2015年度广东省优秀信用企业',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '建材公司获得由第六届华南信用管理论坛组委会、广东省现代服务业联合会授予的“2015年度广东省优秀信用企业”荣誉称号，已连续4年获此殊荣。',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=21',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972429',
    'updatetime' => '1470972439',
    'hitsid' => 'c-1-21',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  20 => 
  array (
    'id' => '20',
    'catid' => '33',
    'typeid' => '0',
    'title' => '一建公司2015年科技创新成果显著',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '一建公司科技创新成果显著。在2015年申报的3个&ldquo;2014年度中国施工企业管理协会科学技术奖&rdquo;项目全部获奖，其中，《建筑幕墙工程绿色施工关   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972414',
    'updatetime' => '1470972427',
    'hitsid' => 'c-1-20',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  19 => 
  array (
    'id' => '19',
    'catid' => '33',
    'typeid' => '0',
    'title' => '广州市建筑科学研究院有限公司获批广州市第四批广州市博',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '广州市人力资源和社会保障局发布&ldquo;关于公布第四批广州市博士后创新实践基地的通知&rdquo;（穗人社函〔2015〕2462号），广州市建筑科学研究院有限   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=19',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972357',
    'updatetime' => '1470972412',
    'hitsid' => 'c-1-19',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '33',
    'typeid' => '0',
    'title' => '广州建筑股份有限公司“超高空屋顶超长天线提升施工方法',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => ' 国家知识产权局发布了&ldquo;关于第十七届中国专利奖授奖的决定&rdquo;（国知发管字[2015]67号），决定授予20项发明、实用新型专利中国专利金奖，5   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=33&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972219',
    'updatetime' => '1470972349',
    'hitsid' => 'c-1-18',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团召开2015年度工作会议',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2016/0813/20160813020622584.jpg',
    'keywords' => '',
    'description' => ' 2015年12月30日下午，集团在建工大厦八楼礼堂召开年度工作会议。会议由集团公司刘玉贵副总经理主持。集团公司领导班子成员，监事会，总部   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470969060',
    'updatetime' => '1470969073',
    'hitsid' => 'c-1-16',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '32',
    'typeid' => '0',
    'title' => '集团公司获2015年度全国优秀博士后工作站',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '广州市建筑集团有限公司企业博士后工作站被评为2015年度全国优秀博士后工作站。',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470969045',
    'updatetime' => '1470969058',
    'hitsid' => 'c-1-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '32',
    'typeid' => '0',
    'title' => '市国资委周建军主任视察广州建筑',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2016/0813/20160813020551713.jpg',
    'keywords' => '',
    'description' => '666666666666666666666666',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=32&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470968989',
    'updatetime' => '1470968995',
    'hitsid' => 'c-1-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>