<?php
return array (
  28 => 
  array (
    'id' => '28',
    'catid' => '34',
    'typeid' => '0',
    'title' => '住房城乡建设部强化“事故信息”报送　迟报漏报谎报瞒报',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '针对一些地区发生房屋市政工程生产安全事故后未按规定及时上报事故信息，严重影响了事故应急处置和安全生产形势研判的情况，住房城乡建设部   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=28',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972890',
    'updatetime' => '1470972911',
    'hitsid' => 'c-1-28',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  36 => 
  array (
    'id' => '36',
    'catid' => '34',
    'typeid' => '0',
    'title' => '住房城乡建设部印发《关于进一步推进工程总承包发展的若',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '为落实《中共中央 国务院关于进一步加强城市规划建设管理工作的若干意见》，住房城乡建设部近日印发《关于进一步推进工程总承包发展的若干   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=36',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470973034',
    'updatetime' => '1470973051',
    'hitsid' => 'c-1-36',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  35 => 
  array (
    'id' => '35',
    'catid' => '34',
    'typeid' => '0',
    'title' => '住房城乡建设部关于重新发布有关专业技术人员资格考试项',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '33333333333333333333333333333333',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=35',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470973022',
    'updatetime' => '1470973032',
    'hitsid' => 'c-1-35',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  34 => 
  array (
    'id' => '34',
    'catid' => '34',
    'typeid' => '0',
    'title' => '建筑业营改增试点工作正式出台',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '财政部和国家税务总局日前联合印发了《关于全面推开营业税改征增值税试点的通知》（财税〔2016〕36号）。通知明确：建筑业增值税税率和增值   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=34',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470973010',
    'updatetime' => '1470973020',
    'hitsid' => 'c-1-34',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  33 => 
  array (
    'id' => '33',
    'catid' => '34',
    'typeid' => '0',
    'title' => '国务院正式公布2016年取消的61项职业资格目录',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '信息来源：广州城建网 作者：丘惠玲 发布日期：2016年2月19日国务院日前发布了《取消一批职业资格许可和认定事项的决定》(国发〔2016〕5   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=33',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972997',
    'updatetime' => '1470973008',
    'hitsid' => 'c-1-33',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  32 => 
  array (
    'id' => '32',
    'catid' => '34',
    'typeid' => '0',
    'title' => '2015年全国建筑业总产值180757亿元　增速大幅跳水',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '66666666666666666666666666666',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=32',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972985',
    'updatetime' => '1470972995',
    'hitsid' => 'c-1-32',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  31 => 
  array (
    'id' => '31',
    'catid' => '34',
    'typeid' => '0',
    'title' => '“一带一路”侧重基础设施建设 利好工程机械',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '77777777777777777777777',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=31',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972970',
    'updatetime' => '1470972983',
    'hitsid' => 'c-1-31',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  30 => 
  array (
    'id' => '30',
    'catid' => '34',
    'typeid' => '0',
    'title' => '互联网+的管理革命 施工企业将迎两化融合',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '88888888888888888888888888',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=30',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972952',
    'updatetime' => '1470972968',
    'hitsid' => 'c-1-30',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  29 => 
  array (
    'id' => '29',
    'catid' => '34',
    'typeid' => '0',
    'title' => '1-7月全国城镇保障性安居工程开工517万套　基本建成425万套',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '2015年，全国计划新开工城镇保障性安居工程740万套（其中各类棚户区580万套），基本建成480万套。截至7月底，已开工517万套，基本建成425万   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=29',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470972913',
    'updatetime' => '1470972950',
    'hitsid' => 'c-1-29',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  37 => 
  array (
    'id' => '37',
    'catid' => '34',
    'typeid' => '0',
    'title' => '1～6月份全国固定资产投资增长9%',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '11111111111111111111111111111111111111111',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=34&id=37',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1470973053',
    'updatetime' => '1470973064',
    'hitsid' => 'c-1-37',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>