<?php
return array (
  2 => 
  array (
    'posid' => '2',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页头条推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '4',
    'siteid' => '1',
    'thumb' => '',
  ),
  1 => 
  array (
    'posid' => '1',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页焦点图推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '1',
    'siteid' => '1',
    'thumb' => '',
  ),
  17 => 
  array (
    'posid' => '17',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频栏目精彩推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '0',
    'catid' => '0',
    'name' => '焦点要闻',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '0',
    'catid' => '0',
    'name' => '下属企业动态',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '0',
    'catid' => '0',
    'name' => '行业资讯',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '0',
    'catid' => '0',
    'name' => '图片新闻',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '0',
    'catid' => '0',
    'name' => '在建重点工程',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '0',
    'catid' => '0',
    'name' => '房地产项目',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  16 => 
  array (
    'posid' => '16',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页每日热点',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  15 => 
  array (
    'posid' => '15',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页头条推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  14 => 
  array (
    'posid' => '14',
    'modelid' => '0',
    'catid' => '0',
    'name' => '视频首页焦点图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页图片推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  10 => 
  array (
    'posid' => '10',
    'modelid' => '0',
    'catid' => '0',
    'name' => '栏目首页推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  9 => 
  array (
    'posid' => '9',
    'modelid' => '0',
    'catid' => '0',
    'name' => '网站顶部推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  8 => 
  array (
    'posid' => '8',
    'modelid' => '30',
    'catid' => '54',
    'name' => '图片频道首页焦点图',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  5 => 
  array (
    'posid' => '5',
    'modelid' => '69',
    'catid' => '0',
    'name' => '推荐下载',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  13 => 
  array (
    'posid' => '13',
    'modelid' => '82',
    'catid' => '0',
    'name' => '栏目页焦点图',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '0',
    'catid' => '0',
    'name' => '新材料产品',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
);
?>